import argparse
import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path


DEFAULT_WORKERS = 1
DEFAULT_REPORT = "video_report.txt"

# Rough reference point for the "+/-6 CRF roughly halves/doubles bitrate"
# rule of thumb, used only to estimate whether a source is already below
# our target bitrate when no embedded CRF value is available. This is a
# coarse heuristic, not a real prediction of encoder output - the
# post-encode size check is the actual safety net.
REFERENCE_CRF = 23.0
REFERENCE_BPP = 0.1

FFPROBE_VIDEO_CMD = [
    "ffprobe",
    "-v",
    "error",
    "-select_streams",
    "v:0",
    "-show_entries",
    "stream=width,height,r_frame_rate",
    "-of",
    "json",
]

FFPROBE_CODEC_CMD = [
    "ffprobe",
    "-v",
    "error",
    "-select_streams",
    "v:0",
    "-show_entries",
    "stream=codec_name,bit_rate",
    "-of",
    "json",
]

FFPROBE_FORMAT_BITRATE_CMD = [
    "ffprobe",
    "-v",
    "error",
    "-show_entries",
    "format=bit_rate",
    "-of",
    "json",
]

FFPROBE_AUDIO_CMD = [
    "ffprobe",
    "-v",
    "error",
    "-select_streams",
    "a",
    "-show_entries",
    "stream=index,codec_name,bit_rate",
    "-of",
    "json",
]

FFPROBE_DURATION_CMD = [
    "ffprobe",
    "-v",
    "error",
    "-show_entries",
    "format=duration",
    "-of",
    "json",
]

FFMPEG_BASE_CMD = [
    "ffmpeg",
    "-hide_banner",
    "-loglevel",
    "error",
    "-y",
]


def parse_report(report_path):
    """
    Read the report generated by the previous script and extract the video paths.
    """

    videos = []

    with open(report_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()

            if not line:
                continue

            if line.startswith((" ", "\t")):
                continue

            if line.startswith("ERROR:"):
                continue

            if line.startswith("No videos"):
                continue

            videos.append(Path(line))

    return videos


def get_video_info(video_path):
    cmd = FFPROBE_VIDEO_CMD + [str(video_path)]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True,
    )

    data = json.loads(result.stdout)
    stream = data["streams"][0]

    width = stream["width"]
    height = stream["height"]

    num, den = stream["r_frame_rate"].split("/")
    fps = float(num) / float(den)

    return width, height, fps


def get_video_codec_and_bitrate(video_path):
    """
    Returns (codec_name, bit_rate_bps or None) for the video stream.
    bit_rate is frequently missing (many containers don't report a
    per-stream figure), in which case the caller should fall back to
    get_container_bitrate().
    """
    cmd = FFPROBE_CODEC_CMD + [str(video_path)]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True,
    )

    data = json.loads(result.stdout)
    streams = data.get("streams", [])

    if not streams:
        return None, None

    stream = streams[0]
    codec_name = stream.get("codec_name")
    bit_rate = stream.get("bit_rate")
    bit_rate = int(bit_rate) if bit_rate is not None else None

    return codec_name, bit_rate


def get_container_bitrate(video_path):
    """
    Overall container bitrate (video + audio combined). Used only as a
    fallback when the video stream itself doesn't report a bit_rate.
    """
    cmd = FFPROBE_FORMAT_BITRATE_CMD + [str(video_path)]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True,
    )

    data = json.loads(result.stdout)
    bit_rate = data.get("format", {}).get("bit_rate")
    print(bit_rate)

    return int(bit_rate) if bit_rate is not None else None


def get_source_crf(video_path):
    """
    Try to recover the CRF a video was originally encoded with, by
    reading the x264 encoder settings string that libx264 embeds in the
    bitstream (as an SEI message) - ffprobe doesn't parse this, so this
    shells out to `mediainfo` instead. Returns None (meaning "unknown",
    not "no CRF was used") if mediainfo isn't installed, the source
    wasn't encoded with x264, or the settings string was stripped.
    """
    try:
        result = subprocess.run(
            ["mediainfo", "--Output=JSON", str(video_path)],
            capture_output=True,
            text=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None

    try:
        data = json.loads(result.stdout)
    except (json.JSONDecodeError, TypeError):
        return None

    tracks = data.get("media", {}).get("track", [])

    for track in tracks:
        if track.get("@type") != "Video":
            continue

        # Field naming for the embedded encoder settings string has
        # varied across mediainfo versions, so scan every string value
        # on the video track rather than relying on one exact key.
        for value in track.values():
            if not isinstance(value, str):
                continue

            match = re.search(r"\bcrf=(\d+\.?\d*)", value)
            if match:
                return float(match.group(1))

    return None


def estimate_bitrate_for_crf(width, height, fps, crf):
    """
    Very rough bits-per-pixel estimate for x264 at a given CRF, anchored
    on the common "+/-6 CRF roughly halves/doubles bitrate" rule of
    thumb. Only used to decide whether it's worth attempting an encode
    when the source's real CRF can't be determined - not a substitute
    for the post-encode size check.
    """
    bpp = REFERENCE_BPP * (2 ** ((REFERENCE_CRF - crf) / 6.0))
    return bpp * width * height * fps


def get_audio_info(video_path):
    """
    Returns (has_audio, codec_name, bit_rate_bps or None).
    bit_rate is often missing for some containers/codecs even when present.
    """
    cmd = FFPROBE_AUDIO_CMD + [str(video_path)]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True,
    )

    data = json.loads(result.stdout)
    streams = data.get("streams", [])

    if not streams:
        return False, None, None

    stream = streams[0]
    codec_name = stream.get("codec_name")
    bit_rate = stream.get("bit_rate")
    bit_rate = int(bit_rate) if bit_rate is not None else None

    return True, codec_name, bit_rate


class ConversionValidationError(Exception):
    """Raised when a converted file fails post-encode integrity checks."""


def get_duration(video_path):
    cmd = FFPROBE_DURATION_CMD + [str(video_path)]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=True,
    )

    data = json.loads(result.stdout)
    duration = data.get("format", {}).get("duration")

    if duration is None:
        raise ConversionValidationError(
            f"{video_path}: ffprobe returned no duration"
        )

    return float(duration)


def validate_conversion(temp_path, original_duration, original_had_audio):
    """
    Confirm the freshly-encoded file is actually intact before it's allowed
    to replace the original. Raises ConversionValidationError on any
    problem; returns the validated new size on success.
    """

    if not temp_path.exists():
        raise ConversionValidationError("ffmpeg reported success but produced no output file")

    new_size = temp_path.stat().st_size

    if new_size == 0:
        raise ConversionValidationError("output file is empty")

    # A failed/truncated encode can still exit 0 (e.g. partial write,
    # dropped frames near the end). ffprobe erroring out here, or the
    # video stream being unreadable, catches that.
    try:
        width, height, fps = get_video_info(temp_path)
    except Exception as e:
        raise ConversionValidationError(f"output has no readable video stream ({e})")

    if width <= 0 or height <= 0:
        raise ConversionValidationError(f"output has invalid dimensions {width}x{height}")

    try:
        new_duration = get_duration(temp_path)
    except Exception as e:
        raise ConversionValidationError(f"could not read output duration ({e})")

    # Tolerance: at least 1s, or 2% of the source duration, whichever is
    # larger. A truncated encode will typically be off by much more than
    # this.
    tolerance = max(1.0, 0.02 * original_duration)
    if abs(new_duration - original_duration) > tolerance:
        raise ConversionValidationError(
            f"duration mismatch: source={original_duration:.1f}s "
            f"output={new_duration:.1f}s (tolerance={tolerance:.1f}s)"
        )

    if original_had_audio:
        try:
            output_has_audio, _, _ = get_audio_info(temp_path)
        except Exception as e:
            raise ConversionValidationError(f"could not verify output audio track ({e})")

        if not output_has_audio:
            raise ConversionValidationError("source had audio but output does not")

    return new_size


def build_ffmpeg_command(
    src,
    dst,
    width,
    height,
    fps,
    has_audio,
    audio_codec,
    audio_bit_rate,
    crf=28,
    preset="slow",
    target_audio_bitrate="128k",
):
    filters = []

    if width > 1280 or height > 720:
        # force_divisible_by=2 avoids odd dimensions that libx264 will
        # reject (or that get silently mis-scaled) when the source
        # resolution isn't a clean multiple of 2 after the aspect-ratio
        # preserving scale.
        filters.append(
            "scale='min(iw,1280)':'min(ih,720)':"
            "force_original_aspect_ratio=decrease:force_divisible_by=2"
        )

    if fps > 30:
        filters.append("fps=30")

    cmd = FFMPEG_BASE_CMD + ["-i", str(src)]

    if filters:
        cmd += ["-vf", ",".join(filters)]

    cmd += [
        "-c:v",
        "libx264",
        "-preset",
        preset,
        "-crf",
        str(crf),
    ]

    if has_audio:
        # `-c:a copy` was the main reason file size barely dropped:
        # a high-bitrate/lossless source audio track gets carried
        # through untouched regardless of how much the video shrinks.
        # Only copy if the audio is already a compact AAC/Opus track
        # at or below our target; otherwise transcode it down.
        already_efficient = (
            audio_codec in ("aac", "opus")
            and audio_bit_rate is not None
            and audio_bit_rate <= 160_000
        )

        if already_efficient:
            cmd += ["-c:a", "copy"]
        else:
            cmd += ["-c:a", "aac", "-b:a", target_audio_bitrate]
    else:
        cmd += ["-an"]

    cmd += ["-movflags", "+faststart", str(dst)]

    return cmd


def convert_video(video_path, crf=28, preset="slow"):
    temp_path = video_path.with_suffix(".tmp" + video_path.suffix)

    try:
        original_size = video_path.stat().st_size
        original_duration = get_duration(video_path)

        width, height, fps = get_video_info(video_path)

        source_codec, source_video_bit_rate = get_video_codec_and_bitrate(video_path)

        if source_codec == "hevc":
            return f"SKIPPED: {video_path} (source is already H.265/HEVC)"

        source_crf = get_source_crf(video_path)

        if source_crf is not None:
            # Encoding at a lower CRF than the source already has means
            # asking for higher quality than it has - that reliably costs
            # more bits, not fewer. Only proceed if our target CRF is the
            # same or higher (= same or lower quality target) than what
            # the source was already encoded with.
            if source_crf > crf:
                return (
                    f"SKIPPED: {video_path} "
                    f"(source already encoded at CRF {source_crf:.1f}, "
                    f"more compressed than requested CRF {crf})"
                )
        else:
            # No embedded CRF info available (hardware encoder, metadata
            # stripped, non-x264 source, mediainfo not installed) - fall
            # back to a rough bitrate comparison instead.
            source_bit_rate = source_video_bit_rate
            if source_bit_rate is None:
                source_bit_rate = get_container_bitrate(video_path)

            estimated_bit_rate = estimate_bitrate_for_crf(width, height, fps, crf)

            if source_bit_rate is not None and source_bit_rate <= estimated_bit_rate:
                return (
                    f"SKIPPED: {video_path} "
                    f"(source bitrate ~{source_bit_rate / 1000:.0f}kbps already at/below "
                    f"estimated ~{estimated_bit_rate / 1000:.0f}kbps for CRF {crf}; "
                    f"no embedded CRF info to check exactly)"
                )

        has_audio, audio_codec, audio_bit_rate = get_audio_info(video_path)

        cmd = build_ffmpeg_command(
            video_path,
            temp_path,
            width,
            height,
            fps,
            has_audio,
            audio_codec,
            audio_bit_rate,
            crf=crf,
            preset=preset,
        )

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise ConversionValidationError(
                f"ffmpeg exited {result.returncode}: {result.stderr.strip()[-500:]}"
            )

        # Exit code 0 alone isn't proof the file is good (truncated
        # writes, dropped streams, etc. can still return 0) - verify
        # before we let this anywhere near the original.
        new_size = validate_conversion(temp_path, original_duration, has_audio)
        
        if new_size >= original_size:
         return (
            f"FAILED: {video_path} "
            "New size is larger, "
            f"({original_size / 1_000_000:.1f}MB -> {new_size / 1_000_000:.1f}MB)"
        )

        # Same filesystem + same directory => atomic rename, so the
        # original is never in a half-replaced state.
        temp_path.replace(video_path)

        saved_pct = (1 - new_size / original_size) * 100 if original_size else 0

        return (
            f"OK: {video_path} "
            f"({original_size / 1_000_000:.1f}MB -> {new_size / 1_000_000:.1f}MB, "
            f"{saved_pct:.0f}% smaller)"
        )

    except Exception as e:
        return f"FAILED: {video_path} ({e})"

    finally:
        # Never leave a stray/bad temp file behind, and never leave one
        # in place if validation rejected it.
        if temp_path.exists():
            temp_path.unlink()


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "report",
        nargs="?",
        default=DEFAULT_REPORT,
        help=f"Report file (default: {DEFAULT_REPORT})",
    )

    parser.add_argument(
        "-w",
        "--workers",
        type=int,
        default=DEFAULT_WORKERS,
        help=f"Worker threads (default: {DEFAULT_WORKERS})",
    )

    parser.add_argument(
        "--crf",
        type=int,
        default=28,
        help="x264 CRF value, higher = smaller/lower quality (default: 28)",
    )

    parser.add_argument(
        "--preset",
        default="slow",
        help="x264 preset, slower = better compression (default: slow)",
    )

    args = parser.parse_args()

    videos = parse_report(args.report)

    print(f"Found {len(videos)} videos to convert.")

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(convert_video, video, args.crf, args.preset): video
            for video in videos
        }

        for i, future in enumerate(as_completed(futures), 1):
            print(future.result())
            print(f"Progress: {i}/{len(videos)}")


if __name__ == "__main__":
    main()